In [1]:
import tensorflow as tf 
import numpy as np

In [2]:
a1 = np.array([
    [1.0,2,3],
    [4.0,5,6],
    [7.0,8,9],
    [2.0,4,6]
])
w1 = np.array([[0.33],[0.66],[0.5]])
w2 = np.array([0.33, 0.66, 0.5])

In [18]:
sess = tf.compat.v1.InteractiveSession()
a = tf.constant(a1)
b = tf.constant(w2)
print(a.eval())
c = tf.multiply(a, b)
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [2. 4. 6.]]
[[0.33 1.32 1.5 ]
 [1.32 3.3  3.  ]
 [2.31 5.28 4.5 ]
 [0.66 2.64 3.  ]]


In [22]:
import numpy as np
import pandas as pd
import pickle
import os

In [48]:
DATA_DIR = './../generated_data'
DIR = 'peru_export'

In [49]:
train_x_neg_file = os.path.join(
        DATA_DIR,
        DIR,
        'ape_negative_samples.pkl'
    )

# train_x_neg_file = os.path.join(
#     DATA_DIR,
#     DIR,
#     'negative_samples_v1.pkl'
# )


In [53]:
with open(train_x_neg_file, 'rb') as fh:
    train_x_neg = pickle.load(fh)


In [55]:
train_x_neg = train_x_neg .astype(np.int32)

In [67]:
train_x_neg[0]

array([[  4,   0,  65,  29, 274,   0,  38],
       [  0,   0,  65,  29, 274,   0,  38],
       [  5,   0,  65,  29, 274,   0,  38],
       [  7,  23,  65,  29, 274,   0,  38],
       [  7,   5,  65,  29, 274,   0,  38],
       [  7,  36,  65,  29, 274,   0,  38],
       [  7,   0, 131,  29, 274,   0,  38],
       [  7,   0, 115,  29, 274,   0,  38],
       [  7,   0, 100,  29, 274,   0,  38],
       [  7,   0,  65,  57, 274,   0,  38],
       [  7,   0,  65,  26, 274,   0,  38],
       [  7,   0,  65,  42, 274,   0,  38],
       [  7,   0,  65,  29, 236,   0,  38],
       [  7,   0,  65,  29, 363,   0,  38],
       [  7,   0,  65,  29,  36,   0,  38],
       [  7,   0,  65,  29, 274,   1,  38],
       [  7,   0,  65,  29, 274,   2,  38],
       [  7,   0,  65,  29, 274,   2,  38],
       [  7,   0,  65,  29, 274,   0,  27],
       [  7,   0,  65,  29, 274,   0,   6],
       [  7,   0,  65,  29, 274,   0,  22]], dtype=int32)

In [58]:
import numpy as np


In [59]:
z = train_x_neg[0]

In [70]:
np.array_split(z,indices_or_sections=z.shape[0],axis=0)

[array([[  4,   0,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  0,   0,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  5,   0,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  7,  23,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  7,   5,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  7,  36,  65,  29, 274,   0,  38]], dtype=int32),
 array([[  7,   0, 131,  29, 274,   0,  38]], dtype=int32),
 array([[  7,   0, 115,  29, 274,   0,  38]], dtype=int32),
 array([[  7,   0, 100,  29, 274,   0,  38]], dtype=int32),
 array([[  7,   0,  65,  57, 274,   0,  38]], dtype=int32),
 array([[  7,   0,  65,  26, 274,   0,  38]], dtype=int32),
 array([[  7,   0,  65,  42, 274,   0,  38]], dtype=int32),
 array([[  7,   0,  65,  29, 236,   0,  38]], dtype=int32),
 array([[  7,   0,  65,  29, 363,   0,  38]], dtype=int32),
 array([[ 7,  0, 65, 29, 36,  0, 38]], dtype=int32),
 array([[  7,   0,  65,  29, 274,   1,  38]], dtype=int32),
 array([[  7,   0,  65,  29, 274,   2,  38]], d