In [20]:
import numpy as np
import pandas as pd
np.set_printoptions(precision=1)

In [21]:
df = pd.read_csv('shuttle2class.txt',sep=' ',header=None)
np.set_printoptions(precision=1)

In [22]:
for c in list(df.columns):
    vals = list(df[c])
    m1 = min(vals)
    m2 = max(vals)
    step = (m2-m1)/10
    _cuts = np.arange(m1,m2+step,step)
    print(_cuts)

[-1.  -0.6 -0.3  0.1  0.5  0.9  1.3  1.6  2.   2.4  2.8]
[-7.  -5.1 -3.2 -1.3  0.6  2.4  4.3  6.2  8.1 10.  11.9]
[-1.2 -0.8 -0.4  0.1  0.5  0.9  1.4  1.8  2.2  2.7  3.1]
[-1.  -0.3  0.3  0.9  1.5  2.1  2.7  3.3  3.9  4.6  5.2  5.8]
[-2.6 -2.2 -1.8 -1.3 -0.9 -0.5 -0.1  0.3  0.7  1.1  1.6]
[-5.8 -4.2 -2.5 -0.9  0.8  2.4  4.1  5.7  7.4  9.  10.6]
[-2.6 -2.  -1.5 -1.  -0.5  0.   0.6  1.1  1.6  2.1  2.6]
[-1.4 -1.  -0.6 -0.3  0.1  0.5  0.8  1.2  1.6  1.9  2.3]
[-1.  -0.7 -0.5 -0.2  0.1  0.4  0.6  0.9  1.2  1.5  1.8]


In [12]:
np.arange(1,10,step= 0.25 )

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])